<?php

  /**
   * Implements hook_menu().
   * I'm testing the application.
   * http://localhost/tripal_test
   */
  function tripal_test_menu() {
	$items = array();

	$items['tripal_test'] = array(
	  'title' => 'Tripal Test',
	  'access callback' => TRUE,
	  'page callback' => 'tripal_test_page',
	  'type' => MENU_NORMAL_ITEM,
	  'menu' => 'navigation',

	);


	return $items;
  }

  // A simple display text Welcome... page tripal_test_page
  function tripal_test_page(){
    return t('Welcome to Tripal test test...');
  }